version: '3.8'

services:
  app:
    build: 
      context: .
    mem_limit: 256m
    cpus: 0.5
    container_name: express-app
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on: 
      - db

  db:
    image: mariadb:11
    container_name: mariadb-db
    deploy: 
      replicas: 1 
    secrets: 
      - secret
    environment:
      MARIADB_PASSWORD_FILE: /run/secrets/mariadb_password 
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - app-network

volumes:
  mariadbdata:

networks:
  app-network:
    driver: bridge 

secrets:
  mariadb_password:
    external: true