version: '3.8'

services:
  app:
    build: 
      context: .
    container_name: express-app
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on: 
      - db

  db:
    image: mariadb:11
    container_name: mariadb-db
    environment:
      - MARIADB_ROOT_PASSWORD=admin
      - MARIADB_DATABASE=meubanco
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=admin
    #env_file:
      #- ./prod.env
    #environment:
      #MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      #MARIADB_DATABASE: ${MARIADB_DATABASE}
      #MARIADB_USER: ${MARIADB_USER}
      #MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - mariadbdata:/var/lib/mysql
    networks:
      - app-network

volumes:
  mariadbdata:

networks:
  app-network:
    driver: bridge 
